[package]
name = "mail_unread_counter"
version = "0.1.0"
authors = ["devan"]
edition = "2018"

[dependencies]
clap = "2.33.3"
reqwest = "0.11.2"
serde_json = "1.0.64"
tokio = { version = "1.4.0", features = ["rt-multi-thread"] }
webbrowser = "0.5.5"
yup-oauth2 = "5.1.0"
